import { motion as Motion } from 'framer-motion'
import { Link } from 'react-router-dom'

const sections = [
    {
        title: '1. Acceptance of These Terms',
        content: (
            <p>
                By accessing the Timmy Tails website, creating an account, or booking a grooming service, you agree to these Terms of Service and our Privacy Policy. Do not use the service if you do not agree with these terms.
            </p>
        )
    },
    {
        title: '2. Our Services',
        content: (
            <p>
                Timmy Tails provides pet-grooming information, online appointment booking, appointment updates, and grooming-style recommendations. Service availability, duration, inclusions, and prices may vary depending on the pet's size, breed, coat condition, behavior, health, and requested service.
            </p>
        )
    },
    {
        title: '3. Appointments, Changes, and Cancellations',
        content: (
            <>
                <ul className='list-disc pl-6 space-y-2'>
                    <li>An appointment is not final until it is accepted or confirmed by Timmy Tails.</li>
                    <li>You must provide accurate booking details and arrive at the agreed time.</li>
                    <li>Please contact us as early as possible when you need to reschedule or cancel.</li>
                    <li>Timmy Tails may reschedule, shorten, decline, or cancel an appointment when necessary for safety, availability, emergencies, incorrect information, or circumstances beyond our reasonable control.</li>
                    <li>Repeated missed appointments or late cancellations may result in booking restrictions.</li>
                </ul>
            </>
        )
    },
    {
        title: '4. Prices and Payment',
        content: (
            <>
                <p>
                    Displayed prices are estimates unless clearly stated otherwise. The final price may change when additional time, handling, products, coat treatment, or services are reasonably required.
                </p>
                <p className='mt-3'>
                    Any added charge should be explained before the additional service is performed whenever reasonably possible. Payment must be made using the payment methods accepted by Timmy Tails.
                </p>
            </>
        )
    },
    {
        title: '5. Pet Health, Behavior, and Safety',
        content: (
            <>
                <p>You are responsible for providing complete and accurate information about your pet, including:</p>
                <ul className='list-disc pl-6 mt-3 space-y-2'>
                    <li>Known health conditions, allergies, injuries, skin problems, or recent medical treatment</li>
                    <li>Aggressive behavior, biting history, severe anxiety, or sensitivity to grooming</li>
                    <li>Special handling instructions and emergency contact details</li>
                </ul>
                <p className='mt-3'>
                    Timmy Tails may stop or refuse a service when continuing could place the pet, staff, or other customers at risk. Grooming may reveal existing skin, coat, ear, nail, or health conditions that were not visible before the appointment.
                </p>
                <p className='mt-3'>
                    In an urgent situation, we may contact you and may recommend or arrange veterinary assistance when reasonably necessary. Veterinary and related expenses remain the owner's responsibility unless applicable law requires otherwise.
                </p>
            </>
        )
    },
    {
        title: '6. AI-Powered Recommendations',
        content: (
            <p>
                Haircut and grooming recommendations generated by automated or machine-learning features are suggestions only. Results may not be suitable for every pet and do not replace the judgment of a professional groomer or veterinarian. Final service decisions should consider your pet's health, coat condition, comfort, breed, and safety.
            </p>
        )
    },
    {
        title: '7. Accounts and Acceptable Use',
        content: (
            <>
                <ul className='list-disc pl-6 space-y-2'>
                    <li>You must provide accurate information and keep your login credentials and OTP codes private.</li>
                    <li>You are responsible for activity performed through your account unless you promptly report unauthorized access.</li>
                    <li>You may not misuse the website, impersonate another person, submit false bookings, interfere with security, introduce malicious code, or attempt unauthorized access.</li>
                    <li>We may suspend or terminate access when these terms are violated or when necessary to protect users, pets, staff, or the website.</li>
                </ul>
            </>
        )
    },
    {
        title: '8. Website Content and Intellectual Property',
        content: (
            <p>
                The Timmy Tails name, logo, website design, text, graphics, and original content are owned by or licensed to Timmy Tails. You may use the website only for personal, lawful purposes. You may not copy, sell, modify, distribute, or commercially exploit protected content without permission.
            </p>
        )
    },
    {
        title: '9. Disclaimers and Limitation of Liability',
        content: (
            <>
                <p>
                    We aim to keep the website accurate and available, but we do not guarantee that it will always be uninterrupted, error-free, or free from technical issues.
                </p>
                <p className='mt-3'>
                    To the fullest extent permitted by law, Timmy Tails is not responsible for indirect, incidental, or consequential losses resulting from website downtime, inaccurate user-provided information, unauthorized account access, or use of automated recommendations.
                </p>
                <p className='mt-3'>
                    Nothing in these terms removes or limits rights or remedies that cannot legally be excluded under applicable Philippine law.
                </p>
            </>
        )
    },
    {
        title: '10. Governing Law and Disputes',
        content: (
            <p>
                These Terms are governed by the laws of the Republic of the Philippines. Before starting formal legal action, both parties should first attempt to resolve concerns in good faith through direct communication. Consumers may also use remedies and complaint channels available under applicable law.
            </p>
        )
    },
    {
        title: '11. Contact Us',
        content: (
            <>
                <p>Questions about these Terms may be sent through:</p>
                <div className='mt-3 space-y-1'>
                    <p><strong>Phone:</strong> (+63) 975-669-2647</p>
                    <p><strong>Address:</strong> Tangos, Baliuag City, Bulacan, Philippines</p>
                    <p>
                        <strong>Online:</strong>{' '}
                        <Link to='/contact' className='text-purple-600 font-semibold hover:text-purple-800'>
                            Contact page
                        </Link>
                    </p>
                </div>
            </>
        )
    }
]

export default function TermsOfService() {
    return (
        <>
            <main className='min-h-screen bg-[#fbf7f1] px-4 pt-24 pb-20 text-[#201711]'>
                <Motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    className='max-w-4xl mx-auto'
                >
                    <div className='text-center mb-12'>

                        <h1 className='text-4xl md:text-5xl font-bold text-gray-900 mb-3'>
                            Terms of Service
                        </h1>

                        <p className='text-gray-600'>
                            Effective date: July 14, 2026
                        </p>
                    </div>

                    <div className='bg-white rounded-3xl shadow-xl border border-gray-100 p-6 md:p-10'>
                        <div className='text-gray-700 leading-relaxed mb-8'>
                            <p>
                                These Terms of Service explain the rules that apply when you access the Timmy Tails website, create an account, book an appointment, or use our grooming-related features.
                            </p>
                        </div>

                        <div className='space-y-8'>
                            {sections.map(({ title, content }) => (
                                <section
                                    key={title}
                                    className='border-b border-gray-100 pb-8 last:border-0 last:pb-0'
                                >
                                    <h2 className='text-xl font-bold text-gray-900 mb-3'>
                                        {title}
                                    </h2>

                                    <div className='text-gray-600 leading-relaxed'>
                                        {content}
                                    </div>
                                </section>
                            ))}
                        </div>

                        <div className='mt-10 rounded-2xl bg-amber-50 border border-amber-200 p-5 text-sm text-amber-900'>
                            Timmy Tails may update these Terms when services, prices, procedures, technology, or legal requirements change. Continued use after an updated version is posted means you accept the revised Terms.
                        </div>
                    </div>
                </Motion.div>
            </main>

        </>
    )
}
